MarsAhletic.WebUI/Controllers/DashboardsController.cs
using MarsAhletic.WebUI.Helpers;
using MarsAhletic.WebUI.Interfaces;
using MarsAhletic.WebUI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Dynamic;
using Microsoft.Reporting.WebForms;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using log4net;

namespace MarsAhletic.WebUI.Controllers
{
    [Authorize]
    public class DashboardsController : Controller
    {
        private ISynchroniseData syncData;

        private ApplicationDbContext appDb;

        private IExternalSystemOperations exOps;

        private ILog logger;

        protected override IAsyncResult BeginExecute(RequestContext requestContext, AsyncCallback callback, object state)
        {

            //Bind ApplicationDb
            appDb = new ApplicationDbContext();

            //Looger
            logger = LogManager.GetLogger(typeof(DashboardsController));

            //Sync Database
            try
            {
                syncData = new SynchroniseData();
                syncData.SyncCompanyData();
                syncData.SyncCurrencies();
                syncData.SyncProducts();
            }
            catch (Exception Ex)
            {
                logger.Error("Veri senkronize edilemedi.", Ex);
            }

            //External Operations
            exOps = new ExternalSystemOperations();


            return base.BeginExecute(requestContext, callback, state);
        }

        protected override void Dispose(bool disposing)
        {
            appDb.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult CreateNewPlanning()
        {

            var model = new TravelPlanViewModel();

            model.TravelId = "#" + Guid.NewGuid().ToString().Replace("-", string.Empty).Substring(0, 8).ToUpper();
            model.ExpanseCenters = new MultiSelectList(appDb.CostCenters.ToList(), "Id", "Name");
            model.ExpanseItems = new MultiSelectList(appDb.ExpanseItems.ToList(), "Id", "Name");


            if (User != null)
            {
                model.NameSurname = User.Identity.GetName();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNewPlanning(TravelPlanViewModel model)
        {
            return View(model);
        }

        public ActionResult CreateNewPurchaseOrder()
        {
            if (!PermissionsHelper.CanAccessPurchasingModule(User.Identity.Name))
            {
                throw new HttpException(403, "Yetersiz Yetki");
            }

            var user = appDb.AppUsers
                .Include("Department")
                .Include("Office")
                .Where(u => u.LoginAccount.UserName == User.Identity.Name && !u.IsDeleted && !u.IsDisabled)
                .FirstOrDefault();


            var model = new PurchaseOrderViewModel();

            if (user != null)
            {
                if (user.Department != null)
                {
                    model.Department = user.Department;
                }

                if (user.Office != null)
                {
                    model.Office = user.Office;
                }
            }

            model.Date = DateTime.Today;
            model.PurchaseOrderId = "#" + Guid.NewGuid().ToString().Replace("-", string.Empty).Substring(0, 8).ToUpper();

            model.Products = new MultiSelectList(appDb.Products.ToList(), "Id", "Name");
            model.Companies = new MultiSelectList(appDb.Companies.ToList(), "Id", "Name");
            model.Currencies = new MultiSelectList(appDb.Currencies.ToList(), "ExternalId", "Name");
            model.BudgetTypes = new MultiSelectList(appDb.BudgetTypes.ToList(), "Id", "Name");

            
           
            if (User != null)
            {
                model.NameSurname = User.Identity.GetName();
            }

            ViewBag.IsPostBack = false;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNewPurchaseOrder(PurchaseOrderViewModel model)
        {


            model.Products = new MultiSelectList(appDb.Products.ToList(), "Id", "Name");
            model.Companies = new MultiSelectList(appDb.Companies.ToList(), "Id", "Name", new string[] { model.CompanyId });
            model.Currencies = new MultiSelectList(appDb.Currencies.ToList(), "ExternalId", "Name");
            model.BudgetTypes = new MultiSelectList(appDb.BudgetTypes.ToList(), "Id", "Name");

            ViewBag.IsPostBack = true;

            if (ModelState.IsValid)
            {

                var purchaseOrder = new PurchaseOrder();
                var user = appDb.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();

                ApplicationUser appUser;

                if (user == null)
                {
                    throw new HttpException(403, "Mevcut kullanıcının giriş hesabı bulunamadı.");
                }
                else
                {
                    appUser = appDb.AppUsers.Where(x => x.LoginAccount.Id == user.Id && !x.IsDisabled && !x.IsDeleted).FirstOrDefault();
                    if (appUser == null)
                    {
                        throw new HttpException(403, "Mevcut kullanıcının giriş hesabı bulunamadı.");
                    }
                }

                //Assign Created By
                purchaseOrder.CreatedBy = appUser;

                //Find Company
                var company = appDb.Companies.Where(c => c.Id.ToString() == model.CompanyId).FirstOrDefault();

                if (company == null)
                {
                    ModelState.AddModelError("", "Seçilen firma veritabanında bulunamadı.");
                    return View(model);
                }

                purchaseOrder.Company = company;

                //Set Other Fields
                purchaseOrder.OrderDate = model.Date;
                purchaseOrder.TotalValue = model.TotalValue;
                purchaseOrder.TotalValueWithoutVAT = model.TotalValueWithoutVAT;
                purchaseOrder.TotalValueWithVAT = model.TotalValueWithVAT;
                purchaseOrder.PurchaseOrderCode = model.PurchaseOrderId;

                //Add Comments
                if (model.AddedComment != null)
                {
                    if (model.AddedComment.Trim() != "")
                    {
                        var comment = new Comment();
                        comment.User = appUser;
                        comment.CommentDate = DateTime.Now;
                        comment.Message = model.AddedComment;

                        purchaseOrder.Comments = new List<Comment>() { comment };
                    }
                }

                var purchaseDetails = new List<PurchaseDetail>();

                foreach (var item in model.PurchaseDetails)
                {
                    var productCode = item.Product.Code;
                    var product = appDb.Products.Where(p => p.Code == productCode).FirstOrDefault();
                    if (productCode == null)
                    {
                        ModelState.AddModelError("", "Seçilen ürünlerden biri veritabanında bulunamadı.");
                        return View(model);
                    }

                    //Create Purchase Detail
                    var purchaseDetail = new PurchaseDetail();
                    purchaseDetail.Amount = item.Amount;
                    purchaseDetail.Product = product;
                    purchaseDetail.Value = item.Value;
                    purchaseDetail.ValueLocal = item.ValueLocal;

                    //Budget Operations
                    if (item.IncludedInBudget)
                    {
                        var opexOrCapex = item.BudgetType.Name;
                        var foundType = appDb.BudgetTypes.Where(x => x.Name == opexOrCapex).FirstOrDefault();

                        if (foundType != null)
                        {
                            purchaseDetail.BudgetType = foundType;
                        }

                        purchaseDetail.BudgetCost = item.BudgetCost;
                        purchaseDetail.IncludedInBudget = item.IncludedInBudget;
                    }

                    //Add Currency
                    var currency = appDb.Currencies.Where(c => c.Name == item.Currency.Name).FirstOrDefault();
                    if (currency == null)
                    {
                        ModelState.AddModelError("", "Seçilen ürünlerden birisine ait para birimi veritabanında bulunamadı.");
                        return View(model);
                    }

                    purchaseDetail.Currency = currency;
                    purchaseDetails.Add(purchaseDetail);

                }

                var documents = new List<Document>();

                //Save Files
                foreach (var item in model.Files)
                {
                    if (item != null)
                    {
                        var targetFolder = Server.MapPath("~/uploads/attachments/");

                        if (!Directory.Exists(targetFolder))
                            Directory.CreateDirectory(targetFolder);

                        var filename = Guid.NewGuid().ToString() + ".bin";
                        var targetPath = Path.Combine(targetFolder, filename);
                        item.SaveAs(targetPath);

                        var document = new Document()
                        {
                            Extension = Path.GetExtension(item.FileName),
                            FullName = item.FileName,
                            StoredName = filename
                        };

                        documents.Add(document);
                    }

MarsAhletic.WebUI/Views/Dashboards/AllPurchaseOrders.cshtml
@{
    ViewBag.Title = "M-Port Tüm Talepler";
}
@using MarsAhletic.WebUI.Models
@model PurchaseListViewModel

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Satınalma Taleplerim</h4>
        <ol class="breadcrumb">
            <li>
                <a href="javascript:void(0);">Satınalma Talepleri</a>
            </li>
            <li>
                Talep Listesi
            </li>
            <li class="active">
                Tüm Satınalma Taleplerim
            </li>
        </ol>
        <p class="text-muted page-title-alt">Sistemde bulunan tüm satınalma taleplerinizi görüntüleyebilirsiniz.</p>
    </div>
</div>

@Html.Partial("PurchaseOrderCountView")


<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">

            <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Talep Numarası</th>
                        <th>Talep Tarihi</th>
                        <th>Talep Durumu</th>
                        <th>Detay</th>
                    </tr>
                </thead>


                <tbody>

                    @foreach (PurchaseOrder item in Model.PurchaseOrders)
                    {
                        <tr>
                            <td>@item.PurchaseOrderCode</td>
                            <td>@item.OrderDate.ToShortDateString()</td>
                            <td>
                                @if (item.MFilesProcessEndedWithApproval && item.MFilesProcessEnded)
                                {
                                    <span class="label label-table label-default">Onaylandı</span>
                                }
                                else if (item.MFilesProcessEnded && !item.MFilesProcessEndedWithApproval)
                                {
                                    <span class="label label-table label-danger">Reddedildi</span>
                                }
                                else
                                {
                                    <span class="label label-table label-warning">Onay Bekliyor</span>
                                }
                            </td>
                            <td>
                                <a href="@Url.Action("ViewPurchaseOrder", "Dashboards", new { id = @item.Id })" class="btn btn-icon waves-effect waves-light btn-default"> <i class="fa fa-search"></i> </a>
                            </td>

                        </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>

@section midjslibs {
    <script src="@Url.Content("~/assets/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.bootstrap.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.buttons.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.bootstrap.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/jszip.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/pdfmake.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/vfs_fonts.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.html5.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.print.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.fixedHeader.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.keyTable.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.responsive.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/responsive.bootstrap.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.scroller.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.colVis.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.fixedColumns.min.js")"></script>
    <script src="@Url.Content("~/assets/pages/datatables.init.js")"></script>

    <script src="@Url.Content("~/assets/plugins/notifyjs/js/notify.js")"></script>
    <script src="@Url.Content("~/assets/plugins/notifications/notify-metro.js")"></script>

    <script src="@Url.Content("~/assets/plugins/parsleyjs/parsley.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/parsleyjs/parsley.tr.js")"></script>

}

@section pagecss {

    <!-- Datatables css -->
    <link href="@Url.Content("~/assets/plugins/datatables/jquery.dataTables.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/buttons.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/fixedHeader.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/responsive.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/scroller.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/dataTables.colVis.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/dataTables.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/fixedColumns.dataTables.min.css")" rel="stylesheet" type="text/css" />


}

@section finaljscodes{

    <script type="text/javascript">
        $(document).ready(function () {

            //Create datatable
            var table = $("#datatable-buttons").DataTable({
                dom: "Bfrtip",
                buttons: [{
                    extend: "copy",
                    className: "btn-sm",
                    text: "Kopyala"
                }, {
                    extend: "csv",
                    className: "btn-sm"
                }, {
                    extend: "excel",
                    className: "btn-sm"
                }, {
                    extend: "pdf",
                    className: "btn-sm"
                }, {
                    extend: "print",
                    className: "btn-sm",
                    text: "Yazdır"
                }],
                responsive: !0,
                "language": {
                    "sDecimal": ",",
                    "sEmptyTable": "Tabloda herhangi bir veri mevcut degil",
                    "sInfo": "_TOTAL_ kayittan _START_ - _END_ arasındaki kayitlar gosteriliyor",
                    "sInfoEmpty": "Kayit yok",
                    "sInfoFiltered": "(_MAX_ kayit icerisinden bulunan)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "Sayfada _MENU_ kayit goster",
                    "sLoadingRecords": "Yukleniyor...",
                    "sProcessing": "Isleniyor...",
                    "sSearch": "Ara:",
                    "sZeroRecords": "Eslesen kayit bulunamadi",
                    "oPaginate": {
                        "sFirst": "Ilk",
                        "sLast": "Son",
                        "sNext": "Ileri",
                        "sPrevious": "Geri"
                    },
                    "oAria": {
                        "sSortAscending": ": artan sutun siralamasini aktiflestir",
                        "sSortDescending": ": azalan sutun soralamasini aktiflestir"
                    }
                }
            });

        });
    </script>


}

MarsAhletic.WebUI/Views/Dashboards/ApprovedPurchaseOrders.cshtml
@{
    ViewBag.Title = "M-Port | Onaylanan Talepler";
}

@using MarsAhletic.WebUI.Models
@model PurchaseListViewModel

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Satınalma Taleplerim</h4>
        <ol class="breadcrumb">
            <li>
                <a href="javascript:void(0);">Satınalma Talepleri</a>
            </li>
            <li>
                Talep Listesi
            </li>
            <li class="active">
                Onaylanan Taleplerim
            </li>
        </ol>
        <p class="text-muted page-title-alt">Tüm onaylanan taleplerinizi görüntüleyebilirsiniz.</p>
    </div>
</div>

@Html.Partial("PurchaseOrderCountView")


<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">

            <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Talep Numarası</th>
                        <th>Talep Tarihi</th>
                        <th>Detay</th>
                    </tr>
                </thead>


                <tbody>

                    @foreach (PurchaseOrder item in Model.PurchaseOrders)
                    {
                        <tr>
                            <td>@item.PurchaseOrderCode</td>
                            <td>@item.OrderDate.ToShortDateString()</td>
                            <td>
                                <a href="@Url.Action("ViewPurchaseOrder", "Dashboards", new {id = @item.Id })" class="btn btn-icon waves-effect waves-light btn-default"> <i class="fa fa-search"></i> </a>
                            </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>

@section midjslibs {
    <script src="@Url.Content("~/assets/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.bootstrap.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.buttons.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.bootstrap.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/jszip.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/pdfmake.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/vfs_fonts.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.html5.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.print.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.fixedHeader.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.keyTable.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.responsive.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/responsive.bootstrap.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.scroller.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.colVis.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.fixedColumns.min.js")"></script>
    <script src="@Url.Content("~/assets/pages/datatables.init.js")"></script>

    <script src="@Url.Content("~/assets/plugins/notifyjs/js/notify.js")"></script>
    <script src="@Url.Content("~/assets/plugins/notifications/notify-metro.js")"></script>

    <script src="@Url.Content("~/assets/plugins/parsleyjs/parsley.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/parsleyjs/parsley.tr.js")"></script>

}

@section pagecss {

    <!-- Datatables css -->
    <link href="@Url.Content("~/assets/plugins/datatables/jquery.dataTables.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/buttons.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/fixedHeader.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/responsive.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/scroller.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/dataTables.colVis.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/dataTables.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/datatables/fixedColumns.dataTables.min.css")" rel="stylesheet" type="text/css" />


}

@section finaljscodes{

    <script type="text/javascript">
        $(document).ready(function () {

            //Create datatable
            var table = $("#datatable-buttons").DataTable({
                dom: "Bfrtip",
                buttons: [{
                    extend: "copy",
                    className: "btn-sm",
                    text: "Kopyala"
                }, {
                    extend: "csv",
                    className: "btn-sm"
                }, {
                    extend: "excel",
                    className: "btn-sm"
                }, {
                    extend: "pdf",
                    className: "btn-sm"
                }, {
                    extend: "print",
                    className: "btn-sm",
                    text: "Yazdır"
                }],
                responsive: !0,
                "language": {
                    "sDecimal": ",",
                    "sEmptyTable": "Tabloda herhangi bir veri mevcut degil",
                    "sInfo": "_TOTAL_ kayittan _START_ - _END_ arasındaki kayitlar gosteriliyor",
                    "sInfoEmpty": "Kayit yok",
                    "sInfoFiltered": "(_MAX_ kayit icerisinden bulunan)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "Sayfada _MENU_ kayit goster",
                    "sLoadingRecords": "Yukleniyor...",
                    "sProcessing": "Isleniyor...",
                    "sSearch": "Ara:",
                    "sZeroRecords": "Eslesen kayit bulunamadi",
                    "oPaginate": {
                        "sFirst": "Ilk",
                        "sLast": "Son",
                        "sNext": "Ileri",
                        "sPrevious": "Geri"
                    },
                    "oAria": {
                        "sSortAscending": ": artan sutun siralamasini aktiflestir",
                        "sSortDescending": ": azalan sutun soralamasini aktiflestir"
                    }
                }
            });

        });
    </script>
}